[project]
site_name = "Blank's CS Learning"
site_description = "空白棱的CS学习笔记"
site_author = "空白棱"
site_url = "https://cyhkbl.github.io/CS-learning/"
copyright = "&copy; 空白棱"
repo_url = "https://github.com/cyhkbl/CS-learning"
nav = [
    {"环境" = [
        { "环境配置" = "环境/环境配置.md" },
        { "包管理" = "环境/包管理.md" }
    ]},
    {"Latex" = [
        { "基础" = "Latex/基础.md" },
        { "图片" = "Latex/图片.md" },
        { "引用" = "Latex/引用.md" }
    ]},
    {"Git" = [
        { "基础" = "Git/基础.md" },
        { "网络配置" = "Git/网络配置.md" },
        { "gitignore" = "Git/gitignore.md" }
    ]},
    {"Python" = [
        { "函数" = "Python/函数.md" },
        { "调试" = "Python/调试.md" },
        { "杂项" = "Python/杂项.md" }
    ]},
    {"网络" = [
        { "网络基础" = "网络/网络基础.md" },
        { "网络连接" = "网络/网络连接.md" },
        { "代理" = "网络/代理.md" },
        { "VPN" = "网络/VPN.md" },
        { "P2P" = "网络/P2P.md" }
    ]},
    {"安全" = [
        { "设备识别与认证" = "安全/设备识别与认证.md" },
        { "网络认证" = "安全/网络认证.md" },
        { "网络安全" = "安全/网络安全.md" }
    ]},
    {"AI" = [
        { "工具" = "AI/工具.md" },
        { "MCP" = "AI/MCP.md" }
    ]},
    {"云" = [
        { "SSH" = "云/SSH.md" },
        { "Azure" = "云/Azure.md" }
    ]},
    {"BME" = [
        { "生物医学信号处理" = "BME/生物医学信号处理.md" }
    ]},
    {"EE" = [
        { "无线电" = "EE/无线电.md" },
        { "数字音频" = "EE/数字音频.md" }
    ]},
    {"CADD" = [
        { "文献阅读" = "CADD/文献阅读.md" }
    }
]

[project.theme]
language = "zh"
favicon = "avatar_without_background.png"
logo = "avatar_without_background.png"
features = [
    "announce.dismiss",
    "content.action.edit",
    "content.action.view",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "header.autohide",
    "navigation.expand",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.path",
    "navigation.prune",
    "navigation.sections",
    "navigation.tabs",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "search.suggest",
    "toc.follow"
]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
palette.primary = "pink"
palette.accent = "pink"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
palette.primary = "purple"
palette.accent = "purple"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.font]
text = "Noto Serif SC"
code = "Jetbrains Mono"